### ISSUE TITLE
Graphql extensions creating com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException

### ISSUE THREAD

**Issue by najeebasaidalavi** [graphql-java-generator/GraphQL-Forum-Maven-Tutorial-client#3]
We are using the Shopify Admin API in GraphQL to create an App. We downloaded the schema from Shopify using the apollo (nodejs) and the POJO fiels were generated automatically. We were able to request the Shopify Storefront APIs successfully, but the Admin APIs have got an extra field "extensions" which makes the deserialisation to fail.
![image](https://user-images.githubusercontent.com/79556348/108943521-031ba680-767f-11eb-938e-6317ad4badd9.png)
The error we are receiving:

`Exception in thread "main" javax.ws.rs.client.ResponseProcessingException: 

com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "extensions" (class com.graphql_java_generator.client.response.JsonResponseWrapper), not marked as ignorable (2 known properties: "data", "errors"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 387] (through reference chain: com.graphql_java_generator.client.response.JsonResponseWrapper["extensions"])
    at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:702)
    at org.glassfish.jersey.client.JerseyInvocation.lambda$invoke$1(JerseyInvocation.java:632)
    at org.glassfish.jersey.client.JerseyInvocation.call(JerseyInvocation.java:654)
    at org.glassfish.jersey.client.JerseyInvocation.lambda$runInScope$3(JerseyInvocation.java:648)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:274)
    at org.glassfish.jersey.internal.Errors.process(Errors.java:205)
    at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:390)
    at org.glassfish.jersey.client.JerseyInvocation.runInScope(JerseyInvocation.java:648)
    at org.glassfish.jersey.client.JerseyInvocation.invoke(JerseyInvocation.java:631)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.method(JerseyInvocation.java:434)
    at org.glassfish.jersey.client.JerseyInvocation$Builder.post(JerseyInvocation.java:335)
    at com.graphql_java_generator.client.QueryExecutorImpl.execute(QueryExecutorImpl.java:142)
    at org.forum.client.util.QueryRootExecutor.shop(QueryRootExecutor.java:20303)
    at org.graphql_forum_sample.client.GraphQLClient.execPartialRequests(GraphQLClient.java:95)
    at org.graphql_forum_sample.client.Main.main(Main.java:19)
Caused by: com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException: Unrecognized field "extensions" (class com.graphql_java_generator.client.response.JsonResponseWrapper), not marked as ignorable (2 known properties: "data", "errors"])
 at [Source: (org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$UnCloseableInputStream); line: 1, column: 387] (through reference chain: com.graphql_java_generator.client.response.JsonResponseWrapper["extensions"])
    at com.fasterxml.jackson.databind.exc.UnrecognizedPropertyException.from(UnrecognizedPropertyException.java:61)
    at com.fasterxml.jackson.databind.DeserializationContext.handleUnknownProperty(DeserializationContext.java:855)
    at com.fasterxml.jackson.databind.deser.std.StdDeserializer.handleUnknownProperty(StdDeserializer.java:1212)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownProperty(BeanDeserializerBase.java:1604)
    at com.fasterxml.jackson.databind.deser.BeanDeserializerBase.handleUnknownVanilla(BeanDeserializerBase.java:1582)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:299)
    at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:156)
    at com.fasterxml.jackson.databind.ObjectReader._bind(ObjectReader.java:2042)
    at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1201)
    at org.glassfish.jersey.jackson.internal.jackson.jaxrs.base.ProviderBase.readFrom(ProviderBase.java:837)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.invokeReadFrom(ReaderInterceptorExecutor.java:233)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor$TerminalReaderInterceptor.aroundReadFrom(ReaderInterceptorExecutor.java:212)
    at org.glassfish.jersey.message.internal.ReaderInterceptorExecutor.proceed(ReaderInterceptorExecutor.java:132)
    at org.glassfish.jersey.message.internal.MessageBodyFactory.readFrom(MessageBodyFactory.java:1072)
    at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:885)
    at org.glassfish.jersey.message.internal.InboundMessageContext.readEntity(InboundMessageContext.java:819)
    at org.glassfish.jersey.client.ClientResponse.readEntity(ClientResponse.java:298)
    at org.glassfish.jersey.client.JerseyInvocation.translate(JerseyInvocation.java:699)`

I have tried adding the @JsonIgnoreProperties(ignoreUnknown = true) to POJOs and also added the deserialization feature to object mapper:
`
ClientConfig config = new ClientConfig();
		ClientRequestFilter tokenHeadersAdder = new ClientRequestFilter()
		{
			@Override
			public void filter(ClientRequestContext ctx) throws IOException
			{
				final Map<String, List<Object>> headers = ctx.getHeaders();
				headers.put("X-Shopify-Access-Token", Collections.singletonList(".......access_token....."));
			}
		};
		Client client = ClientBuilder.newClient(config);
		client.register(tokenHeadersAdder);
		
ObjectMapper om = new ObjectMapper();
om.disable(DeserializationFeature.FAIL_ON_UNKNOWN_PROPERTIES);
om.disable(DeserializationFeature.FAIL_ON_IGNORED_PROPERTIES);
om.disable(DeserializationFeature.FAIL_ON_INVALID_SUBTYPE);
om.disable(DeserializationFeature.FAIL_ON_MISSING_CREATOR_PROPERTIES);
om.disable(DeserializationFeature.FAIL_ON_MISSING_EXTERNAL_TYPE_ID_PROPERTY);
om.disable(DeserializationFeature.FAIL_ON_UNRESOLVED_OBJECT_IDS);

queryExecutor = new QueryRootExecutor("https://storilabs.myshopify.com/admin/api/2021-01/graphql.json",client,om);`

Any help is greatly appreciated! Thanks!

**Comment by etienne-sf** [comment]
Hello,

  I can't find this "extensions" field, in the GraphQL spec.

In the GraphQL spec [available here](https://github.com/graphql/graphql-spec/blob/main/spec/Section%207%20--%20Response.md), the response can only contain two fields: "data", and an optional "errors".

So the current version actually doesn't manage this extensions field. So you get this error.


Can you update the generated code, like described below ?

Update the com.graphql_java_generator.client.response.JsonResponseWrapper (found in the target/generated-sources/graphql-maven-plugin folder), by adding the _extensions_ field like this:

```
public class JsonResponseWrapper {

	/**
	 * This contains the data coming from the GraphQL part. The issue here is that it contains data that depends on the
	 * GraphQL schema. So we just collect the parsed Json, which will be mapped later to the relevant Java POJO
	 */
	public JsonNode data;

	@JsonDeserialize(contentAs = Error.class)
	public List<Error> errors;

	public JsonNode extensions;
}
```

If it doesn't work, can you provide me a code sample, so that I can repeat and properly correct that ?


Etienne

**Comment by najeebasaidalavi** [comment]
Hi Etienne,
Thanks for the reply.
Some responses have got the "Extensions" field in them, in addition to the data and errors. Please check it out [here](https://www.howtographql.com/graphql-java/7-error-handling/)  and [here](https://spec.graphql.org/June2018/#sec-Response-Format). 
And I could not find the com.graphql_java_generator.client.response.JsonResponseWrapper in the target/generated-sources/graphql-maven-plugin folder. The generated-sources contain only the org.forum.client and org.forum.client.util packages.
The  com.graphql_java_generator.client.response.JsonResponseWrapper class is present in the Maven Dependencies, but I'm not able to edit it.
Will be great if you can help here. 
Thanks again!

**Comment by najeebasaidalavi** [comment]
Hi Etienne,
Thanks so much for your suggestion on changing the JsonResponseWrapper, I changed the code and added it to my code instead of adding it as a maven dependency. It is working fine now. I have been working graphql on this for past 3-4 days and your solution was the one that worked for me.

**Comment by etienne-sf** [comment]
Ok, great!


Thanks for your response. I'll embed that in the next release. 

:)

Étienne

**Comment by etienne-sf** [comment]
You can check the 1.12.3 version, released today
